config/routes.rb
Rails.application.routes.draw do

  resources :users
  resource :session
  resources :goals
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :commentable, polymorphic: true

end

app/models/goal.rb
class Goal < ActiveRecord::Base

  validates :body, presence: true

  belongs_to :user
  has_many :comments, as: :commentable

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :session_token, :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token
  has_many :goals
  has_many :comments, as: :commentable
  has_many :comments
  attr_reader :password

  def self.find_by_credentials(username,password)
    user = User.find_by(username: username)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save
    self.session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def require_login
    redirect_to new_session_url unless current_user
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def new
    @goal = Goal.new
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def index
    @goals = Goal.where("privacy = 'public' OR user_id = #{current_user.id}")
    p @goals
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def destroy
    goal = Goal.find(params[:id])
    goal.destroy
    render :index
  end

  private

  def goal_params
    params.require(:goal).permit(:body,:privacy,:completed)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_credentials(user_params[:username],user_params[:password])
    if @user
      login(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = ["user not found"]
      render :new
    end
  end

  def new
    @user = User.new
  end

  def destroy
    logout
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username,:password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to goals_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
  end

  private

  def user_params
    params.require(:user).permit(:username,:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<form class="" action="/goals/<%= @goal.id %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="Body">Body</label>
  <input type="text" name="goal[body]" id="Body" value="<%= @goal.body %>">

  <label for="Private">Private</label>
  <input type="radio" name="goal[privacy]" id="Private" value="private">

  <label for="Public">Public</label>
  <input type="radio" name="goal[privacy]" id="Public" value="public"><br><br>

    <label for="Completed">Completed</label>
    <select class="" id="Completed" name="goal[completed]">
      <option value="Yes">Yes</option>
      <option value="No">No</option>
    </select>

  <input type="submit" name="name" value="Edit Goal">
</form>

app/views/goals/index.html.erb
<h1>All Goals</h1>

<% if @goals %>
  <% @goals.each do |goal| %>
    <ul>
      <li><%= link_to "#{goal.body}", goal_url(goal) %></li>
    </ul>
  <% end %>
<% end %>

<%= link_to "Create A Goal", new_goal_url %>

app/views/goals/new.html.erb
<h1>Create Goal</h1>

<form class="" action="/goals/" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="Body">Body</label>
  <input type="text" name="goal[body]" id="Body" value="<%= @goal.body %>"><br><br>

  <label for="Private">Private</label>
  <input type="radio" name="goal[privacy]" id="Private" value="private">

  <label for="Public">Public</label>
  <input type="radio" name="goal[privacy]" id="Public" value="public"><br><br>

  <label for="Completed">Completed</label>
  <select class="" id="Completed" name="goal[completed]">
    <option value="Yes">Yes</option>
    <option value="No">No</option>
  </select>

  <label for="color_gold">Gold</label>
  <input type="checkbox" name="goal[color][]" id="color_gold" value="gold">

  <label for="color_red">Red</label>
  <input type="checkbox" name="goal[color][]" id="color_red" value="red">

  <label for="color_purple">Purple</label>
  <input type="checkbox" name="goal[color][]" id="color_purple" value="purple">

  <input type="submit" name="name" value="Create Goal">
</form>

app/views/goals/show.html.erb
<p>
  <%= @goal.body %>
</p>

<%= link_to "Goals Index", goals_url %>

<%= link_to "Edit Goal", edit_goal_url(@goal)  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
  <ul>
    <li><%= current_user.username %>  <%= button_to "Logout", session_url, method: :delete %> </li>
  </ul>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<p>
  Sign Up
</p>

<form class="" action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="Username">Username</label>
  <input type="text" name="user[username]" id="Username" value="<%= @user.username %>">
  <label for="Password">Password</label>
  <input type="text" name="user[password]" id="Password" value="<%= @user.password %>">

  <input type="submit" name="name" value="Sign Up">
</form>